version: "3"

services:
  database:
    image: "postgres:14.1-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
      TZ: "Asia/Seoul"
      PGTZ: "Asia/Seoul"
    volumes:
      - ./db-data:/var/lib/postgresql/data
  redis:
    image: "redis:6.2-alpine"
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database